-- Check row counts in raw tables
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count
FROM CLAY_REVENUE_INTELLIGENCE.RAW.CUSTOMERS
UNION ALL
SELECT 'USAGE_LEDGER', COUNT(*)
FROM CLAY_REVENUE_INTELLIGENCE.RAW.USAGE_LEDGER
UNION ALL
SELECT 'WORKFLOW_RUNS', COUNT(*)
FROM CLAY_REVENUE_INTELLIGENCE.RAW.WORKFLOW_RUNS
UNION ALL
SELECT 'SUPPORT_TICKETS', COUNT(*)
FROM CLAY_REVENUE_INTELLIGENCE.RAW.SUPPORT_TICKETS;

-- Check dbt mart outputs
SELECT COUNT(*) AS customer_health_rows
FROM CLAY_REVENUE_INTELLIGENCE.DBT_NSHANKAR.CUSTOMER_HEALTH;

SELECT COUNT(*) AS churn_score_rows
FROM CLAY_REVENUE_INTELLIGENCE.DBT_NSHANKAR.CHURN_RISK_SCORES;

SELECT *
FROM CLAY_REVENUE_INTELLIGENCE.DBT_NSHANKAR.SIGNAL_FEED;
